Repository OswaldoPineda/Solidus-Untitled, pull requests merged in 2020-12, with the labels that each got.

#6 Feature/products
  app/javascript/components/App.js
  app/javascript/components/footer/footer.scss
  app/javascript/components/products/CardProduct.js
  app/javascript/components/products/Products.js
  app/javascript/components/products/cardProduct.scss
  app/javascript/components/products/products.scss
  app/javascript/components/what-is-untitled/what-is-untitled.scss
  app/javascript/styles/_colors.scss
  app/javascript/styles/general.scss
Labels: Ready for Review, feature

#8 Create navigation bar
  app/javascript/components/App.js
  app/javascript/components/header/Header.js
  app/javascript/components/header/header.scss
  app/javascript/components/navigation/Navigation.js
  app/javascript/components/navigation/navigation.scss
  app/javascript/styles/general.scss
Labels: Ready for Review, feature

#7 Truncate in title card products
  app/javascript/components/products/cardProduct.scss
Labels: Ready for Review, bug

#9 Create template for pull request
  pull_request_template.md
Labels: Chore, Ready for Review

#13 Create menu
  app/javascript/components/navigation/Menu.js
  app/javascript/components/navigation/Navigation.js
  app/javascript/components/navigation/menu.scss
  app/javascript/components/navigation/navigation.scss
  app/javascript/styles/_colors.scss
Labels: Ready for Review, feature

#14 Fix styles in page
  app/javascript/components/App.js
  app/javascript/components/footer/footer.scss
  app/javascript/components/navigation/menu.scss
  app/javascript/components/navigation/navigation.scss
  app/javascript/components/what-is-untitled/what-is-untitled.scss
  app/javascript/styles/_variables.scss
  app/javascript/styles/general.scss
  package-lock.json
Labels: Ready for Review, feature
